### ISSUE TITLE
Adding a CI/CD Documentation and Website Generation System for Hattip

### ISSUE THREAD

**Issue by William-McGonagle** [hattipjs/hattip#20]
I'm working on another bun project and I found that you can get more contributors with a website. I built a really simple website and documentation generation tool if you want to add it to your project. Its under the MIT License- I'm just sending it around the bun community so it gains some more traction. If you want to check it out, it's [right here](https://github.com/William-McGonagle/bun-doc). It's all integrated with Github Actions so all you have to do is add the code to GitHub actions and then you're are all set. If you don't want to, just let me know and close this issue- good luck with your project!

Also, just a tip, add a bunch of issues you need help with and label them "good first issue" because then people will see your project from places like goodfirstissues.com.

**Comment by brillout** [comment]
Thanks for the tip!

**Comment by cyco130** [comment]
Cool project, I'll definitely check it out. I agree we need a website and we've already registered hattipjs.org.

@brillout here is the author of vite-plugin-ssr and I'm the author of Rakkas. Both are SSR frameworks with static site generation capabilities. Rakas runs on HatTip and VPS can run on HatTip (and other envs). So I think we're kind of obligated to use one of those instead of Next.js for the project website :)

Thanks for the other tips too, it will definitely improve our visibility.
